// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Neon (Postgres) only. Placeholder used during build when DATABASE_URL isn't set;
// the app uses the real DATABASE_URL at runtime.
const databaseUrl =
  process.env.DATABASE_URL ||
  "postgresql://build:build@localhost:5432/build?sslmode=disable";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
